graph TD;
N0["source_item"]
N1["def"]
N0 --> N1
N2["func_signature"]
N0 --> N2
N3["identifier: main2"]
N2 --> N3
N4["("]
N2 --> N4
N5[")"]
N2 --> N5
N6["statement"]
N0 --> N6
N7["expression_statement"]
N6 --> N7
N8["expr"]
N7 --> N8
N9["binary_expr"]
N8 --> N9
N10["expr"]
N9 --> N10
N11["identifier: i"]
N10 --> N11
N12["="]
N9 --> N12
N13["expr"]
N9 --> N13
N14["literal"]
N13 --> N14
N15["dec: 1"]
N14 --> N15
N16[";"]
N7 --> N16
N17["end"]
N0 --> N17
