graph TD;
N0["ENTRY: ENTRY"]
N1["EXIT: EXIT"]
N2["CONDITION: i<5"]
N3["BASIC_BLOCK: i=i+1"]
N4["BASIC_BLOCK: end loop"]
N5["BASIC_BLOCK: a=7"]
N0 --> N2
N2 --> N3
N3 --> N2
N2 --> N4
N4 --> N5
N5 --> N1
