graph TD;
N0["source"]
N1["source_item"]
N0 --> N1
N2["def"]
N1 --> N2
N3["func_signature"]
N1 --> N3
N4["identifier"]
N3 --> N4
N5["main"]
N4 --> N5
N6["("]
N3 --> N6
N7[")"]
N3 --> N7
N8["statement"]
N1 --> N8
N9["expression_statement"]
N8 --> N9
N10["expr"]
N9 --> N10
N11["binary_expr"]
N10 --> N11
N12["expr"]
N11 --> N12
N13["identifier"]
N12 --> N13
N14["a"]
N13 --> N14
N15["="]
N11 --> N15
N16["expr"]
N11 --> N16
N17["literal"]
N16 --> N17
N18["dec"]
N17 --> N18
N19["1"]
N18 --> N19
N20[";"]
N9 --> N20
N21["end"]
N1 --> N21
